### ISSUE TITLE
Capacitor use

### ISSUE THREAD

**Issue by pathnirvana** [nydasco/nydas_keyboard_v2#6]
Really great design. Thank you ☺️
Can it be panelized in a 5x5 matrix?
If I omit the capacitor what would happen?

**Comment by nydasco** [comment]
Certainly can't see why it wouldn't be possible to do a 5x5. It all depends on the company you use and their costings. Given you usually have to get 5 prints minimum, you'd need to have a think about the best dimensions to go with.

If you don't want RGB, no need for the capacitor. It's used to stabilise the current and ensure the LED doesn't flicker or not light if there are minute power fluctuations through the circuit. Not using them isn't going to break anything, and depending on the number of switches you may be able to get away without any, but they are 'best practice', generally with a single larger one at the start of the chain.

**Comment by pathnirvana** [comment]
Many thanks for the answer
Yes the jlcpcb has a promotion for PCBs under 10×10cm area.

The reason I asked was that one of the other micropads I built with a different ameoba PCB was flickering at high brightness settings and it didn't have the capacitors
